//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mediagallery
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string caption { get; set; }
        public Nullable<int> published { get; set; }
        public Nullable<int> ordering { get; set; }
    }
}
