//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace education.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class category
    {
        public category()
        {
            this.contents = new HashSet<content>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> level { get; set; }
        public string path { get; set; }

        [Required(ErrorMessage = "Vui long nhap title")]
        public string title { get; set; }
        public string note { get; set; }
        public string discription { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<content> contents { get; set; }
    }
}
