//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.usersinroles = new HashSet<usersinrole>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<usersinrole> usersinroles { get; set; }
    }
}
